{
 "title": "Sondes Blackbox",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(probe_success,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(probe_success{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "sonde",
    "query": {
     "query": "label_values(probe_success{namespace=~\"$namespace\", cluster=~\"$cluster\"},sonde)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "États des sondes Blackbox",
   "type": "stat",
   "description": "Une sonde est comptabilisée \"Up\" si au moins 50% des requêtes effectuées pendant la dernière minute ont réussi.\nInversement, une sonde est comptabilisée \"Down\" si strictement moins de 50% des requêtes effectuées pendant la dernière minute ont échoué.\nCela permet de stabiliser le compteur si une sonde échoue une fois de manière passagère.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by(target) (avg_over_time(probe_success{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"}[1m])) >= 0.5) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(max by(target) (avg_over_time(probe_success{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"}[1m])) < 0.5) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux de disponibilité",
   "type": "stat",
   "description": "Taux de disponibilité des sondes. Seules celles qui ont un taux inférieur à 95% sont affichées.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(target) (probe_success{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Vue d'ensemble",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max by (target) (probe_success{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"})",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "probe_http_status_code{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"}[$__range])"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"}[$__range])"
    },
    {
     "expr": "probe_tls_version_info{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"}"
    },
    {
     "expr": "probe_http_version{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"} > 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{cluster=~\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"} - time()"
    },
    {
     "expr": "probe_ssl_last_chain_info{cluster=\"$cluster\", namespace=~\"$namespace\", sonde=~\"$sonde\"}"
    }
   ]
  },
  {
   "title": "Disponibilité à travers le temps",
   "type": "state-timeline",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "panelId": 1 }
   ]
  }
 ]
}