blackbox:
  fullnameOverride: blackbox-exporter-prom
  kind: Deployment
  pspEnabled: false
  resources:
    limits:
      cpu: "1"
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 25Mi
  serviceAccount:
    create: false
  podSecurityContext:
    fsGroup: 1000885000
    runAsGroup: 1000885000
    runAsNonRoot: true
    runAsUser: 1000885000
  config:
    modules:
      http_200_204_403:
        http:
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_status_codes:
          - 200
          - 204
        prober: http
        timeout: 5s
      http_check:
        http:
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        prober: http
        timeout: 5s
      icmp_check:
        icmp:
          preferred_ip_protocol: ipv4
        prober: icmp
        timeout: 5s
      tcp_check:
        prober: tcp
        timeout: 5s
application: cpin
sondes:
  - name: console-external
    interval: 60s
    cible: https://console.external.cpin.numerique-interieur.com/
    type: http
    module: http_check
    interval: 30s
    metricRelabelings:
      - destLabel: service
        value: console-external
  - name: vault-external
    interval: 60s
    cible: https://vault.external.cpin.numerique-interieur.com/
    type: http
    module: http_check
    interval: 30s
    metricRelabelings:
      - destLabel: service
        value: vault-external
  - name: gitlab-external
    interval: 60s
    cible: https://gitlab.external.cpin.numerique-interieur.com/
    type: http
    module: http_check
    interval: 30s
