application: cpin
sondes:
  - name: console-cpin-scw
    cible: https://console.dso.cpin.numerique-interieur.fr/
    module: http_check
  - name: vault-cpin-scw
    cible: https://vault.dso.cpin.numerique-interieur.fr/
    module: http_check
  - name: gitlab-cpin-scw
    cible: https://gitlab.dso.cpin.numerique-interieur.fr/
    module: http_check
  - name: sonar-cpin-scw
    cible: https://sonar.dso.formation.numerique-interieur.fr/
    module: http_check
  - name: argocd-cpin-scw
    cible: https://argocd.dso.formation.numerique-interieur.fr/
    module: http_check
  - name: harbor-cpin-scw
    cible: https://harbor.dso.formation.numerique-interieur.fr/
    module: http_check


