blackbox:
  extraEnvFrom:
    - secretRef:
        name: sec-blackbox
  fullnameOverride: blackbox-exporter-prom
  kind: Deployment
  pspEnabled: false
  resources:
    limits:
      cpu: "1"
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 25Mi
  serviceAccount:
    create: false
  securityContext:
    runAsGroup: 1000965000
    runAsNonRoot: true
    runAsUser: 1000965000
  podSecurityContext:
    runAsGroup: 1000965000
    runAsNonRoot: true
    runAsUser: 1000965000
  config:
    modules:
      http_200_204_403:
        http:
          tls_config:
            insecure_skip_verify: true
          proxy_from_environment: true
          skip_resolve_phase_with_proxy: true
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_status_codes:
          - 200
          - 204
        prober: http
        timeout: 5s
      http_check:
        http:
          tls_config:
            insecure_skip_verify: true
          skip_resolve_phase_with_proxy: true
          proxy_from_environment: true
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        prober: http
        timeout: 5s