{{ if .Values.proxy }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sec-blackbox
spec:
  vaultAuthRef: vault-auth # Nom du VaultAuth, toujours vault-auth dans le cas de CPiN
  mount: stsup # Nom du coffre dans vault (<organisation>-<nom du projet>)
  path: mi # Chemin vers le secret
  type: kv-v2 # Type du coffre, toujours kv-v2 dans le cas de CPiN
  destination:
    name: sec-blackbox # Nom du secret kubernetes que l'opérateur va créer
    create: true
{{ end }}